services:
  postgres:
    image: postgres:15-alpine
    container_name: user_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres12345
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
